apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: profile
        image: nginx:1.20 
      volumes:
        - name: content
          configMap:
            name: dev-profile  