apiVersion: apps/v1
kind: Deployment
metadata:
  name: ordering
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: payment
        image: nginx:1.19 # Staging-specific nginx version
      volumes:
        - name: content
          configMap:
            name: staging-ordering