apiVersion: apps/v1
kind: Deployment
metadata:
  name: ordering
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: ordering
          image: nginx:1.20.0
          resources:
            limits:
              memory: 512Mi
      volumes:
        - name: content
          configMap:
            name: staging-ordering
