apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
      variant: prod

resources:
- ../../../base/ordering
- configmap.yaml

patches:
- patch: |-
    - op: replace
      path: /spec/ports/0/nodePort
      value: 30083
  target:
    kind: Service
    name: ordering
- path: patch.yaml
