apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-ordering
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/dludnai/promotions.git'
    targetRevision: HEAD
    path: stages/prod/ordering
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
          - CreateNamespace=true  