apiVersion: apps/v1
kind: Deployment
metadata:
  name: ordering
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: ordering
          image: nginx:1.20.0
      volumes:
        - name: content
          configMap:
            name: prod-ordering
      securityContext:
        runAsUser: 1000
