apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: payment
        image: nginx:1.18 # Prod-specific nginx version
      volumes:
        - name: content
          configMap:
            name: prod-payment