apiVersion: apps/v1
kind: Deployment
metadata:
  name: ordering
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ordering
  template:
    metadata:
      labels:
        app: ordering
    spec:
      containers:
      - name: ordering
        image: nginx:latest # Base on nginx
        volumeMounts:
        - name: content
          mountPath: /usr/share/nginx/html
          readOnly: true
        ports:
        - containerPort: 80
      volumes:
      - name: content
        configMap:  
          name: content  
