apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
      - name: payment
        image: nginx:latest # Base on nginx
        volumeMounts:
        - name: content
          mountPath: /usr/share/nginx/html
          readOnly: true
        ports:
        - containerPort: 80
      volumes:
      - name: content
        configMap:
          name: content 