apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
      variant: dev

resources:
- ../../../base/payment
- configmap.yaml

patches:
- patch: |-
    - op: replace
      path: /spec/ports/0/nodePort
      value: 30081
  target:
    kind: Service
    name: payment
- path: patch.yaml