apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-payment
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/dludnai/promotions.git'
    targetRevision: HEAD
    path: base/payment
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev
  syncPolicy:
    automated: {}