apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: profile
        image: nginx:1.18 
      volumes:
        - name: content
          configMap:
            name: prod-profile