name: Update Manifests

on:
  workflow_dispatch:
    inputs:
      memoryLimit:
        description: 'Memory limit for the container'
        required: true
        default: '512Mi'

jobs:
  release_dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/download/v4.6.1/yq_linux_amd64 -O /usr/bin/yq && sudo chmod +x /usr/bin/yq

      - name: Update Memory Limit in Dev Environment
        run: |
          yq e ".spec.template.spec.containers[0].resources.limits.memory = \"${{ github.event.inputs.memoryLimit }}\"" -i stages/dev/ordering/patch.yaml
          git add stages/dev/ordering/patch.yaml
          git commit -m "Update Memory Limit to Dev Env" || echo "No changes to commit in Dev Env"
          git pull --rebase
          git push

  release_stage:
    runs-on: ubuntu-latest
    needs: release_dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"  

      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/download/v4.6.1/yq_linux_amd64 -O /usr/bin/yq && sudo chmod +x /usr/bin/yq

      - name: Update Memory Limit in Staging Environment
        run: |
          yq e ".spec.template.spec.containers[0].resources.limits.memory = \"${{ github.event.inputs.memoryLimit }}\"" -i stages/staging/ordering/patch.yaml
          git add stages/staging/ordering/patch.yaml
          git commit -m "Update Memory Limit in Staging Env" || echo "No changes to commit in Staging Env"
          git pull --rebase
          git push

  release_prod:
    runs-on: ubuntu-latest
    needs: release_stage
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"   

      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/download/v4.6.1/yq_linux_amd64 -O /usr/bin/yq && sudo chmod +x /usr/bin/yq

      - name: Update Memory Limit in Prod Environment
        run: |
          yq e ".spec.template.spec.containers[0].resources.limits.memory = \"${{ github.event.inputs.memoryLimit }}\"" -i stages/prod/ordering/patch.yaml
          git add stages/prod/ordering/patch.yaml
          git commit -m "Add Security Context in Prod Env" || echo "No changes to commit in Prod Env"
          git pull --rebase
          git push
