name: Update Nginx Version

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Nginx version to use'
        required: true
        default: 'latest'

jobs:
  update-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
      
      - name: Pull latest changes
        run: git pull origin main
      
      - name: Update Nginx version and push changes
        run: |
          sed -i "s|image: nginx:.*|image: nginx:${{ github.event.inputs.version }}|" stages/dev/ordering/patch.yaml
          git add stages/dev/ordering/patch.yaml
          git commit -m "Update Nginx version to ${{ github.event.inputs.version }} in dev"
          git push
